#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use OAuth2Demo\Client\Command\CollectEggsCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CollectEggsCommand);
$application->run();